"""Check generated bytes against the published manifest with LF and CRLF inputs."""
from pathlib import Path
import hashlib
import json
import shutil
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[1]
sha = lambda p: hashlib.sha256(p.read_bytes()).hexdigest()
manifest = json.loads((ROOT / 'artifact-sha256.json').read_text(encoding='utf-8'))
expected = {e['path']: e['sha256'] for e in manifest['files']}
with tempfile.TemporaryDirectory(prefix='tacticalgo-vis-rebuild-') as tmp:
    temp_root = Path(tmp).resolve()
    assert temp_root.parent == Path(tempfile.gettempdir()).resolve()
    assert temp_root.name.startswith('tacticalgo-vis-rebuild-')
    copied = temp_root / ROOT.name
    shutil.copytree(ROOT, copied, ignore=shutil.ignore_patterns('*.zip', '__pycache__'))
    originals = {name: (copied / name).read_bytes() for name in
                 ['web/index.html', 'web/feel.css', 'web/feel.js']}
    def run(name):
        subprocess.run([sys.executable, '-X', 'utf8', str(copied / 'qa' / name)],
                       check=True, capture_output=True)
    for newline in (b'\n', b'\r\n'):
        for name, data in originals.items():
            (copied / name).write_bytes(data.replace(b'\r\n', b'\n').replace(b'\n', newline))
        run('build-review.py')
        run('build-storyboard.py')
        for name in ('REVIEW.html', 'ANIMATION_STORYBOARD.html'):
            assert b'\r' not in (copied / name).read_bytes(), name
            assert sha(copied / name) == expected[name], name
    for name, data in originals.items():
        (copied / name).write_bytes(data)
    run('package-review.py')
    assert (copied / 'artifact-sha256.json').read_bytes() == (ROOT / 'artifact-sha256.json').read_bytes()
print(json.dumps({'rebuild': 'pass', 'input_line_endings': ['LF', 'CRLF'],
                  'output': 'UTF-8/LF', 'published_html_and_manifest_hashes': 'unchanged'}))
